# Generated by Django 2.1.7 on 2019-08-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeather', '0002_city_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
