# Generated by Django 2.1.7 on 2019-08-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeather', '0003_auto_20190803_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
